// <auto-generated />
using CocktailApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CocktailApi.Migrations
{
    [DbContext(typeof(CocktailContext))]
    [Migration("20210126000012_CocktailTableMigrationSeed")]
    partial class CocktailTableMigrationSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CocktailApi.Models.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Cocktails");
                });
#pragma warning restore 612, 618
        }
    }
}
